### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Some-random** [facebookresearch/WavAugment#10]
I downloaded dev-clean of librispeech and unzipped it in WavAugment/examples/python/data. When I run `python librispeech_selfsupervised.py`, the error below occurred. Can someone please look into it?

```
Traceback (most recent call last):
  File "librispeech_selfsupervised.py", line 193, in <module>
    for batch in dataloader:
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
past shape: torch.Size([1, 16000])
x shape: torch.Size([1, 16000])
    return self._process_data(data)
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/project/tools/env/tf2.0_py3.6_all_luban_20200616/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "librispeech_selfsupervised.py", line 62, in __getitem__
    past = self.augment_past(past)
  File "librispeech_selfsupervised.py", line 115, in __call__
    x, src_info=src_info, target_info=target_info)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by eugene-kharitonov** [comment]
@Some-random Hey, thanks for the issue.
I think I've fixed it; please let me know if you still have problems.
